### ISSUE TITLE
merge multiple requests into a single typedefinition

### ISSUE THREAD

**Issue by ivanhofer** [inngest/typedwebhook.tools#21]
Great tool! I played around a bit and tested it with an API I recently created.

## problem

The problem I saw is that types are generated only per request. So if my API would allow multiple tipes for a single property, I would have to merge them manually. Here an example:

_payload 1_
```json
{
   "data": "Hello"
}
```

_payload 2_
```json
{
   "data": null
}
```

When I send those payloads to the webhook, I get two different type definitions, I then have to manually merge myself.

## suggestion

I would love to see a toggle somewhere in the UI that makes it possible to listen to multiple requests and then generating a type from it. In the end I would expect to be presented with the following type for the example payloads above:

```ts
interface Payload {
   data: string | null
}
```

**Comment by tonyhb** [comment]
Yeah, this is a solid idea, and something we need to look at!  We need to do the opposite of type refinement - "widening" - by merging > 1 type definition for the same request.

This is something we'll take care of in our [event schemas](https://github.com/inngest/event-schemas) repository which does the type generation for us, and then add here.

A question to consider in terms of ux: should we select the incoming webhooks that we want to "merge" together via the UI, or merge everything?  The first seems way more powerful, but more complex.

**Comment by ivanhofer** [comment]
Making a toggle somewhere where you all upcoming request get merged is probably easier to implement but could also lead to some frustration: when someone makes 3 requests and then realizes he forgot to enable the merging feature. He then would need to send those requests again.

**Comment by tonyhb** [comment]
@ivanhofer I've added logic to the underlying type generation library here: https://github.com/inngest/event-schemas/pull/17.    

As you asked, this allows us to take two arbitrary payloads, create types for them, and merge the types together — generating a new type definition which suits both payloads.

Next steps are implementing this new logic within the webassembly build of our type generation, then adding a UI to allow types to be merged in the UI.  The hard work is done!  🎉

**Comment by tonyhb** [comment]
The UI is now live!  You can shift-click to select multiple types, and the generated types will be valid for all selected requests:


https://user-images.githubusercontent.com/306177/164975763-373ebbe5-25c4-44fc-bcc5-fb49a6fe98fd.mov

**Comment by ivanhofer** [comment]
Pretty cool! 😎 Thanks!
